# -*- coding: utf-8 -*-
"""model-kerusakan

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HhlnaEKGxr40kluhBCZSGHE0arTG8GSi
"""

import pandas as pd

kerusakan = pd.read_csv('data_kerusakan.csv')

kerusakan

data = kerusakan.copy()

target = 'Kerusakan'

data.head()

target_mapper = {'Internet Limit':0, 'Router Reset':1, 'Network Cable Unplugged':2, 'Router/Switch Rusak':3}

def target_encode(val):
  return target_mapper[val]

data['Kerusakan'] = data['Kerusakan'].apply(target_encode)

data

X = data.drop('Kerusakan', axis=1)
Y = data['Kerusakan']

X

Y

from sklearn.svm import SVC
model = SVC()
model.fit(X, Y)

import pickle
pickle.dump(model, open('model-kerusakan.pkl', 'wb'))